library(ggplot2)
library(RColorBrewer)
NEI <- readRDS("C:\\Users\\WELCOME\\Desktop\\coursera\\exdata_data_NEI_data (1)\\summarySCC_PM25.rds")
SCC <- readRDS("C:\\Users\\WELCOME\\Desktop\\coursera\\exdata_data_NEI_data (1)\\Source_Classification_Code.rds")
setwd("C:\\Users\\WELCOME\\Desktop\\coursera\\exdata_data_NEI_data (1)")
png("plot6.png", width = 480, height = 480)
vehicle  <- grepl("vehicle", SCC$SCC.Level.Two, ignore.case=TRUE)
SCC_Vehicle <- SCC[vehicle, ]
NEI_SCC_Merge <- merge(NEI, SCC_Vehicle, by="SCC")
NEI_SCC_Bal_LA <- subset(NEI_SCC_Merge, fips=='24510' | fips=='06037')
NEI_SCC_Bal_LA$City <- ifelse(NEI_SCC_Bal_LA$fips=="24510", "Baltimore", "Los Angeles")
Emissions <- aggregate(Emissions ~ year + City,NEI_SCC_Bal_LA, sum)
g <- ggplot(Emissions, aes(x=year, y=Emissions, color=City))
g + geom_line() + ggtitle("Total Emissions From Motor Vehicle Sources Baltimore Vs. Los Angeles") + xlab("Year") + ylab("Total Emissions PM2.5 Tons") + scale_color_brewer(palette = "Set1")
dev.off()