library(ggplot2)
library(RColorBrewer)
NEI <- readRDS("C:\\Users\\WELCOME\\Desktop\\coursera\\exdata_data_NEI_data (1)\\summarySCC_PM25.rds")
SCC <- readRDS("C:\\Users\\WELCOME\\Desktop\\coursera\\exdata_data_NEI_data (1)\\Source_Classification_Code.rds")
setwd("C:\\Users\\WELCOME\\Desktop\\coursera\\exdata_data_NEI_data (1)")
png("plot3.png", width = 480, height = 480)
Baltimore_MARYLAND <- subset(NEI, fips=='24510')
Emissions_BALMA <- aggregate(Emissions ~ year + type, Baltimore_MARYLAND, sum)
g <- ggplot(data = Emissions_BALMA, aes(x=year, y=Emissions, color=type))
g + geom_line() + scale_color_brewer(palette = "Set1") + ylab("Total Emissions PM2.5 Tons Baltimore") + xlab("Year")+ ggtitle("Baltimore Emissions Per Type")
dev.off()